name: Terraform CI

on:
  pull_request:
    branches: ["dev", "stage", "main"]
  push:
    branches: ["dev", "stage", "main"]

permissions:
  contents: read

concurrency:
  group: terraform-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: terraform validate (${{ matrix.env }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env: [dev, stage, prod]

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform init (no backend)
        run: terraform -chdir=envs/${{ matrix.env }} init -backend=false

      - name: Terraform validate
        run: terraform -chdir=envs/${{ matrix.env }} validate

  lint_security:
    name: fmt + tflint + tfsec
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0

      - name: Initialize TFLint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONFIG_PATH="$(pwd)/.tflint.hcl"
          echo "Using config: $CONFIG_PATH"
          tflint --init --config "$CONFIG_PATH"

      - name: TFLint envs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONFIG_PATH="$(pwd)/.tflint.hcl"

          for d in envs/*; do
            if [ -d "$d" ] && ls "$d"/*.tf >/dev/null 2>&1; then
              echo "=== tflint: $d ==="
              tflint --chdir "$d" --config "$CONFIG_PATH"
            fi
          done

      - name: TFLint modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONFIG_PATH="$(pwd)/.tflint.hcl"

          for d in modules/*; do
            if [ -d "$d" ] && ls "$d"/*.tf >/dev/null 2>&1; then
              echo "=== tflint: $d ==="
              tflint --chdir "$d" --config "$CONFIG_PATH"
            fi
          done

      - name: tfsec (security scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra/terraform
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: v1.28.13